version: '2'

services:

  uwsgi:
    build: .
    container_name: kspu-password-uwsgi
    command: uwsgi --ini uwsgi.ini
    volumes:
      - .:/code
#      - static:/code/static/
#      - sock:./mysite.sock
    ports:
      - "8800:8800"
    environment:
      - DJANGO_DEBUG=1
      - DATABASE_NAME=DATABASE_NAME
      - DATABASE_USER=DATABASE_USER
      - DATABASE_PASSWORD=DATABASE_PASSWORD
      - DATABASE_HOST=DATABASE_HOST
      - DATABASE_PORT=5432

    restart: always

