# Generated by Django 2.0.5 on 2018-05-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20180517_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='tsnak4@yandex.ru', max_length=256),
        ),
    ]
