# Generated by Django 2.0.5 on 2018-05-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_admin_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='fullname',
            field=models.TextField(),
        ),
    ]
