# Generated by Django 2.0.5 on 2018-05-23 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20180518_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRecoveryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=256)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 5, 23, 13, 46, 45, 614540))),
            ],
        ),
    ]
