# Generated by Django 2.0.5 on 2018-05-25 04:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_passwordrecoverydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordrecoverydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 25, 4, 44, 28, 741221, tzinfo=utc)),
        ),
    ]
