# Generated by Django 2.0.5 on 2019-01-16 08:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_auto_20190116_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='login',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordrecoverydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 16, 8, 26, 31, 406535, tzinfo=utc)),
        ),
    ]
