# Generated by Django 2.0.5 on 2019-01-18 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20190116_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='path',
            field=models.TextField(default='uid=tsnakk,ou=staff,ou=infosys,ou=cit,ou=administration,ou=kspu,dc=kspu,dc=ru'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordrecoverydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 18, 8, 34, 34, 532487, tzinfo=utc)),
        ),
    ]
