# Generated by Django 2.0.5 on 2019-01-21 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_auto_20190118_1535'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationData',
        ),
        migrations.AlterField(
            model_name='passwordrecoverydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 7, 10, 17, 576513, tzinfo=utc)),
        ),
    ]
