# Generated by Django 2.0.5 on 2019-01-21 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20190121_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('login', models.TextField()),
                ('position', models.TextField()),
                ('number', models.TextField()),
                ('year', models.TextField()),
                ('password', models.TextField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='passwordrecoverydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 7, 14, 4, 767508, tzinfo=utc)),
        ),
    ]
