# Generated by Django 2.0.5 on 2019-01-23 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_auto_20190121_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='partonymic',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationdata',
            name='surname',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordrecoverydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 8, 43, 5, 506333, tzinfo=utc)),
        ),
    ]
