# Generated by Django 2.0.5 on 2019-01-30 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_auto_20190123_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField()),
                ('username', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='passwordrecoverydata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 30, 7, 50, 38, 509299, tzinfo=utc)),
        ),
    ]
